### ISSUE TITLE
New Tab-Button/Strg+T is not working with Fx 45.0

### ISSUE THREAD

**Issue by Miccovin** [tabkit/tabkit2#102]
Hi, after the Firefox-Update to version 45.0 I cannot open a new Tab with the button or with the shortcut Strg+T. It works without any activated addon. But with this Addon activated it fails.

UPDATE: 
A new tab is opened - at the end of the tablist. 
BUT: In the tablist it has no label and I cant activate this tab. I can click the X on it to close it - but nothing happens. After restarting the firefox these weird "new tab" is gone.

Please fix this problem for this essential function.

My System:
Windows 8.1-64
Firefox 45.0-64
Tab Kit 2nd Edition 0.12.5

Thx,
Mic

PS: Do we need an extra-extension like "tabgruppen" after panorama was deleted? I am not sure, but i think not.

**Comment by Coruscate5** [comment]
Yeah, broken for me as well. I literally use this everyday (since TabMixPlus scans show exploits) - I'll take a look at the code tonight if it's still broken

**Comment by Miccovin** [comment]
Thx :)

**Comment by PikachuEXE** [comment]
Let me take a look later
I am only free on Sunday :(

**Comment by Sytric** [comment]
(Coruscate alt) Yeah, took a glance - I have no idea what's going on in there. I'll leave it to the creator :)

..but may still poke around at some point since multi-row tabs are my lifeblood

**Comment by LookingForWayOut** [comment]
Just adding my name to list on this since I was about to post the same thing. I have tried cleaning out cache, history, and disabling all other addons. With TK2, I can not even open addons or options since they require new tabs (I open everything in tabs). But I can with about:addons, etc. This started happening yesterday, but I do not recall FF asking to be updated, but I am at v45, Windows 10 Home (sucks, I know, I need PRO). I have done all I know short of removing the addon and/or refreshing Firefox.

**Comment by Boovov** [comment]
I think this might be happening because they changed how FF handles tab in this patch i believe by removing the tab grouping stuffs.

> XUL
>     Tab Groups have been removed.

https://developer.mozilla.org/en-US/Firefox/Releases/45

so the probably removed some stupid tags from the code that are not referencing properly now or something.

I also am hitting this problem, so put myself on here so I can see when a reply occurs.  hope this info can narrow it down for you PikachuEXE.

Love tabkit, keep up the great work.

**Comment by GTX2GvO** [comment]
Adding myself to the list of people with this issue.
In the meanwhile have to use "Vertical Tabs Reloaded" to get the tabs where I need them, but it ain't TabKit2 though. :(

I'll be eagerly waiting for a fix. :)

**Comment by PikachuEXE** [comment]
It takes a while to fix this problem
This extension used to use hacky way to determine where to move the new tab
Now it doesn't work anymore and I need to re-code the behaviour
It won't be fixed this week :S 

Unless you need FF 45 very much, I suggest you to workaround this problem by downgrading to 38.x for now.

**Comment by GTX2GvO** [comment]
Don't worry. Take your time to fix it. :)
Like I said, I have a temp solution that does the basic trick. (move tabs vertically to the right)

I'd rather wait several weeks for a good fix, then to be served a botchy patch today.

**Comment by ajuniper** [comment]
One workaround on Linux I've found is to open a new window and then drag the tab to the desired location in the original window.
Also, "open link in new tab" will work as expected and then you can manually move the tab to the desired location.

**Comment by PikachuEXE** [comment]
# Progress Report
- Restored new tab behaviour for:
  - search with keyword in context menu
  - search with search bar

I kind of know how the methods should be called
Now I need to trace all methods that the extension is trying to detect & run custom code
And use another method to detect & run custom code

## Code before
Tab Kit uses some bad practices (which are banned in FF ESR 45)
to detect what user has performed and do appropriate actions (grouping, sorting, etc.)

## Code After (being done)
Tab Kit uses some practices recommended by Mozilla themselves (they have recommended that way for long, even since FF 4 I think)
Which won't break unless FF's internal structure is changed
This means the "patches" depend heavily on FF's internal structure and might break across versions
So to keep less messy, only most recent 2 ESR versions will be actually supported (e.g. FF45 & 38 for now)
FF 31 will still be **declared** as supported in extension but not guranteed to be working (blame FF team :P)

Now I need to find all the remaing methods (like those used by Ctrl+T) and apply the patch
Should be done next week

**Comment by desirepl** [comment]
I'll add my 5 cents to this.
Code broken in the part where external clicks on links open tabs too.
Previously all my external links was opened in the current window and new tabs, but after upgrade ff to 45 this changed, and with this extension enabled each click at link in any external app creates new window instead of new tab.

**Comment by industriflow** [comment]
I almost downgraded to FFox ESR 38, but I need 64-bit FFox, and that doesn't exist in ESR 38 (at least not in stable version; perhaps in the old beta channel?).
PikachuEXE, let me know if you want a beta tester for your new patch fixing issues #101 and #102.
Thanks for your efforts to get this programmed and patched.

**Comment by PikachuEXE** [comment]
@industriflow 
Thanks for volunteering
I will release a version tonight (even not all issues are fixed)
You can test that version after its released!

Not sure where to get 64bit of FF ESR 45 portable :(

**Comment by PikachuEXE** [comment]
Released a new version
Please test!
https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/

**Comment by desirepl** [comment]
External links opened in current window, ok.
Coloring ok.

**Comment by aernhart** [comment]
Version 0.12.6 works for me so far - upon installation, the screen flickered a bit and a later look at journalctl shows that gnome-shell restarted at that time, so I suspect a crash and recovery there, but no crash of other apps or data loss. While I suspect that Tabkit2 triggered that restart, I won't say Tabkit2 is at fault, or where the bug is.

Once the screen settled down, a dialog reported: "Sorry, Tab Kit 2nd Edition does not support App Tabs in Vertical mode". I clicked OK, and my many tabs from previous session appeared as I wanted, down the left side of screen, in what I'd call Vertical mode. So that message was odd.

And while I haven't tried really testing it, all seems to work fine so far.

Thank you!

PS: This is 0.12.6 in FF 45.0.1 on Fedora 23 (Firefox provided as part of OS) and the Gnome 3.18.2 using X backend, plus Nvidia drivers on a Macbook pro.

**Comment by PikachuEXE** [comment]
@aernhart 
I think you got that message since you have pinned tab(s)
They are/were called App Tabs

**Comment by JRPtau** [comment]
Some error message (twice) for each pinned tab, but they opened normally.
"Open link in a new tab" works normally.
Ctrl-T does not work. Thus opened tabs can not be closed. "Close tabs below" also does not help.
"Tab Kit | New tab here" - same problem

Win7, SP1; FF 45.0.1

**Comment by GTX2GvO** [comment]
Sweet. Looks like the issues I had are fixed in 0.12.6 :)
Will report if there is anything else bugging, but so far nothing out here. (for me at least)

**Comment by Miccovin** [comment]
Works fine. Great Work! :+1:

**Comment by aaronELBorg** [comment]
Agreed.  How people can work without this add-on is beyond me.

Many thanks, PikachuEXE!!!

**Comment by industriflow** [comment]
Found problems moving tabs between groups. 
How to reproduce: 
1. Set up three tab groups.
2. Drag a tab from one group into another. Try dragging various tabs several times.
Problem:  sometimes it works, but often the entire destination group disappears while hovering the moving tab over it (during dragging). Sometimes the group reappears. But sometimes it doesn't, and there's no way to get to those missing tabs. The space occupied by the former tab group becomes "gray."
(Also, a huge thank-you to PikachuEXE for advancing progress toward making this all work!)

**Comment by PikachuEXE** [comment]
@industriflow You might be talking about #92 or a new issue
But they are not related to this issue :P (not new tab bahaviour problem)

Feel free to open new issue if you can't find an existing one

**Comment by industriflow** [comment]
I'll open a new issue for this, and respond there. It may become 106.

**Comment by DShillito** [comment]
The fix seems to work for me also :)
Thanks for fixing this so quickly.  Like others, I find this addin invaluable.

Any idea when it will get verified by Mozilla, so I can turn xpinstall.signatures.required back on?
(No rush... I'm grateful you have fixed the problem so soon :) )

**Comment by PikachuEXE** [comment]
@DShillito 
You can turn it back on if you only install Tab Kit from
https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/

**Comment by DShillito** [comment]
@PikachuEXE 
Superb, I thought that's what I did before, but I must have been mistaken.
All seems good now.
Thanks again :)

**Comment by sniffer** [comment]
For me this is not quite working as expected. I have a session with 300+ tabs that I restore on profile startup. Now when I hit Ctrl+T, the new tab opens as the last tab on the vertical tree tab hierarchy (on the bottom of the list). Before the new tab used to open after the active tab group.

Also there is a no longer necessary option in Settings/Experimental to enable Panorama.

**Comment by PikachuEXE** [comment]
@sniffer 
What OS/Firefox are you using?
Is it possible to reproduce it with a clean profile? (new profiles can be created with profile manager extension)

>>> Also there is a no longer necessary option in Settings/Experimental to enable Panorama.
It's for FF 38, which will still be supported until next ESR released

**Comment by sniffer** [comment]
I'm on a mixed release Ubuntu, running latest stable release 'Wily' as a base, FF from repo.

I've created a new profile, installed TK, and it still persists. Changed no TK options - should be defaults.

The option 'Ungrouped new tabs should be positioned' is 'next to the current tab' which is set to 'to the right of it and its recent children'. So I think the settings are correct.

The only other addon I have on a new profile is Ubuntu modifications.

**Comment by PikachuEXE** [comment]
OK thanks for sharing your current options
I will try to reproduce it with those settings

**Comment by PikachuEXE** [comment]
Anddddd more issues fixed in `0.12.7`
https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/0.12.7

**Comment by LookingForWayOut** [comment]
Mozilla thinks it knows best, will not let me install an addon they not verified.

**Comment by aaronELBorg** [comment]
Look in the faq here:
https://wiki.mozilla.org/Add-ons/Extension_Signing

**Comment by PikachuEXE** [comment]
zzzzzzzzzzzzzzz
Again?

And they still haven't fixed the tool for client side extension signing :S

**Comment by industriflow** [comment]
0.12.7 not available at mozilla.org, but it was before. I installed it.
Now I can't get it for another machine from the URL given above:  
https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/0.12.7 
"The page or file you requested wasn't found on our site." is what my browser loads now.

Is there a place to d/l and test earlier versions of TK2, like 0.12.5 for FF 44?

**Comment by PikachuEXE** [comment]
https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/
Here :)

**Comment by Subreptivus** [comment]
> https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/
Here 

Yes, but there is no v0.12.7, I didn't have time to download and now it's gone.

**Comment by Coruscate5** [comment]
Working great for me also. 

Haven't tested more recent updates since the first fix - just tweaked about:config for the signing issue for the time being.

**Comment by Blessun** [comment]
Hello, windows 10 x64, FF 45.0.2, version 0.12.9
http://take.ms/5c7Ya
not working

**Comment by sniffer** [comment]
The issue I reported in my previous comment is now gone as of 0.12.8 and Ctr+T is working as expected. I can confirm that it is also working on FF 46 from ubuntu 15.10 repo.

**Comment by PikachuEXE** [comment]
@Blessun 
What do you use to open new tab?
Also what's your config about new tab position?

I need more details to reproduce your issue

**Comment by Blessun** [comment]
Use nothing 
Just tabkit does not open a new tab from bookmarks 
What information is needed? I will provide

**Comment by PikachuEXE** [comment]
OK so you are trying to open a bookmarked entry but it is not opened
Could you give me a screenshot like below so I can know your settings?
![screen shot 2016-04-28 at 3 08 26 pm](https://cloud.githubusercontent.com/assets/1018543/14877982/2405d1ee-0d53-11e6-91f0-950a5bcfa5d3.png)

**Comment by Blessun** [comment]
http://take.ms/5c7Ya

**Comment by PikachuEXE** [comment]
Thanks
Let me fix it this weekend

**Comment by PikachuEXE** [comment]
@Blessun 
I have tried to reproduce your issue and failed to do so
Below is my TabKit preference in my profile for testing
Could you post all the screenshots where there is any preference different from my one?

![1](https://cloud.githubusercontent.com/assets/1018543/14941819/2459aa68-0fdc-11e6-956c-8f464b817167.png)
![2](https://cloud.githubusercontent.com/assets/1018543/14941820/254f5df0-0fdc-11e6-835e-f99c70b3995b.png)
![3](https://cloud.githubusercontent.com/assets/1018543/14941821/26540912-0fdc-11e6-8c8e-be32c72ff562.png)
![4](https://cloud.githubusercontent.com/assets/1018543/14941823/2737c0ee-0fdc-11e6-8662-d8fbb3d3f9e3.png)
![5](https://cloud.githubusercontent.com/assets/1018543/14941825/2812a42a-0fdc-11e6-8edd-9231108c2a50.png)
![6](https://cloud.githubusercontent.com/assets/1018543/14941826/28c9f5f8-0fdc-11e6-91ce-5233fbea464d.png)

**Comment by Blessun** [comment]
1. http://take.ms/b5Q8e
2. http://take.ms/nlhhK
3. http://take.ms/4ta5R
4. http://take.ms/psrJB
5. http://take.ms/h729j
6. http://take.ms/8Vkrv

**Comment by PikachuEXE** [comment]
I can't reproduce the issue with your posted settings
But it could be due to I am on developement branch
Let me upload a new version so you can try that again

**Comment by PikachuEXE** [comment]
Can you try again with latest version?

**Comment by industriflow** [comment]
Another new-tab problem:  in the current version (TabKit2 ver. 0.12.12 on Firefox 46.0.1 64-bit) there's only one place from which new tabs won't open:  the open bookmarks folder. To reproduce, click Bookmarks, Show All Bookmarks, and double-click a bookmark within the bookmarks "Library."

Before the current version, new tabs wouldn't open from the URL address bar. But, now they do.

**Comment by PikachuEXE** [comment]
I have fixed it yesterday and released a new version
Awaiting approval

**Comment by industriflow** [comment]
"New tab" operations like Ctrl-T and new tab from Bookmarks and URL bar operations were working perfectly again for me under Firefox 46 and TK2 ver. 0.12.14.

**Comment by Magnus909** [comment]
Same problem again with FF 47. Using multiple row tabs.
