### ISSUE TITLE
Color Tab Group => New Extension?

### ISSUE THREAD

**Issue by misakitchi** [tabkit/tabkit2#141]
Your extension is very good but i only use the feature to have color for tabs group
Can you extract this feature to a new extension?
Because i have Palemoon 27 with TST. But with the full Tab Kit 2, there is some bugs with TST...
Thanks and sorry for my bad english

**Comment by PikachuEXE** [comment]
The coloring is attached to tab group defined in the extension
It's not a standalone function since Firefox/Palemoon does not have built-in tab-grouping

It's mainly done inside [`colorizeTab`](https://github.com/tabkit/tabkit2/blob/master/src/content/tabkit.js#L4699)
(The link might not point exactly on the method in the future)
Feel free to let the TST author know and write its own coloring feature.
