### ISSUE TITLE
[Bug] Lull The Tabs - Break Tree Tabs Indentation

### ISSUE THREAD

**Issue by misakitchi** [tabkit/tabkit2#144]
I just install this plugins: "Lull The Tabs" to unload inactives tabs
Its working but when tabs are unloaded it break the Tabs Tree Style... :(
I don't know if the bug is from this plugin or yours... :(
Can you do something?

Before:
![palemoon27 - lull the tabs - before](https://user-images.githubusercontent.com/9465756/38455146-430cbfa0-3a63-11e8-9126-c848b593db48.jpg)

After:
![palemoon27 - lull the tabs - after](https://user-images.githubusercontent.com/9465756/38455147-4882e748-3a63-11e8-9a04-d21da0875baf.jpg)

Thanks! :)

**Comment by misakitchi** [comment]
Hello! Some news on this issue?

**Comment by JustOff** [comment]
Thank you, [I tried to use your API](https://github.com/JustOff/lull-the-tabs/commit/806c2a7c0f678f4737d59dbdfaf6f61daa3ba4c4), but unfortunately had no success.

Here is the [test version](https://github.com/JustOff/lull-the-tabs/releases/download/1.4.2/lull-the-tabs-1.4.3b2.xpi), could you please check what's going wrong?

**Comment by PikachuEXE** [comment]
Since we have listener to move subtree of closed tab into closed tab's parent after tab removed
https://github.com/tabkit/tabkit2/blob/v0.13.3/src/content/tabkit.js#L1020
https://github.com/tabkit/tabkit2/blob/v0.13.3/src/content/tabkit.js#L3083
https://github.com/tabkit/tabkit2/blob/v0.13.3/src/content/tabkit.js#L3094-L3100

Can you try to call the methods after removing tabs to see if it works?

**Comment by JustOff** [comment]
Thanks for the hint, everything goes perfect if I remove `groupid`, `tabid` and `possibleparent` attributes before closing the tab.

Perhaps it makes sense you add the following function to API:
```
      ignoreTab: function(tab) {
        // This should be called only if you have manually handled the children
        // of this tab and need to remove it without affecting the tree
        tab.removeAttribute("groupid");
        tab.removeAttribute("tabid");
        tab.removeAttribute("possibleparent");
      },
```

One more thought, for performance reason I want to ask you not to call `tk.updateIndents()` at the end of `addChildTabs` to speed up the bulk operations that my extension uses. You can provide a separate alias function to `tk.updateIndents()` in the API, but in my case it isn't even necessary, since the indents will be updated by `sortgroup_onTabRemoved` when the tab is deleted.

**Comment by JustOff** [comment]
Thank you, [I added](https://github.com/JustOff/lull-the-tabs/commit/741aa51e490070022eecc76cbe2865fae75ac72b) the call to `resetTab` and now LTT can properly restore TK2 trees.

[lull-the-tabs-1.4.3b3.xpi](https://github.com/JustOff/lull-the-tabs/releases/download/1.4.2/lull-the-tabs-1.4.3b3.xpi)

**Comment by PikachuEXE** [comment]
@misakitchi 
Please install both "dev" version of extensions and see if there is any issue

**Comment by misakitchi** [comment]
Hi! Thanks!
It seems to be working! :)
Thanks to you two! ^_^

**Comment by PikachuEXE** [comment]
Then let me release it
