### ISSUE TITLE
Moving Tab Groups between windows: broken

### ISSUE THREAD

**Issue by bibbs** [tabkit/tabkit2#64]
// this had worked in 07-2013 but somehow it broke again (ff 30, tk2 0.11.2)
// old issue link: https://github.com/tabkit/tabkit2/issues/3
// maybe an regression, or something which never made it from the "dev" version?

description:
If I try to move a tab group to another window by shift-drag,
a) it moves only the last two tabs of the group
b) the moved tabs are not grouped anymore in the target window
c) "moved" tabs remain as a copy in the source window, thus making it a copy operation instead of moving (on the opposite, dragging a single tab always means "moving")

**Comment by industriflow** [comment]
I still get somewhat random (but never successful) results when I try to move or copy a tab group to a new window. (I can reliably move one tab to another open window.)

Sometimes only the one tab I clicked on (while holding either Shift or Ctrl in Windows) gets moved.
Lately (TK2 v. 0.12.14 in Firefox 46) sometimes the one tab appears twice in the new window.

The general problem with moving/copying a tab group has existed across many versions.

This "move group" or "copy group" feature would be a WONDERFULLY useful thing, and extremely helpful for keeping groups and windows organized.

**Comment by industriflow** [comment]
Still broken:  can't move (or copy) a tab group to a new window. 

Tested using TabKit2 v 0.12.15, in Firefox ESR v 45.6.0, and no other add-ons enabled.

Expected behavior:  collapse a tab group by double-clicking it; shift-drag or ctrl-drag the group to an already open new Firefox window; the tab group should be moved (or copied) to the new window.

Actual behavior:  only one tab is copied to the new window; sometimes a second tab is copied too and duplicated as two identical tabs in the new window. Tested this with both empty windows and those with several tabs in them.

This hasn't worked for many versions. It would be extremely useful to keep groups in windows organized.

Thank you, PikachuEXE, for all your good work on TabKit 2nd edition!

**Comment by bibbs** [comment]
confirming industriflow's post
[tk2 0.12.15, firefox esr 45.7]

example:
- source window: 
  group of 4 tabs, "a" "b" "c" "d"
- on shift dragging this group to another window, there appear:
  tabs "d" and "a", which are non-grouped, (and in wrong order)
- after the operation in the source window I see:
  tabs "b" "c" "d"
  (meaning that "a" has moved, while "d" was copied; "b" and "c" untouched)

thanks for all your efforts!

btw, are there any tutorials on how to build the extension from git? 
I'm not being that skilled, but I occasionally I could try to fork and test something by myself without ruining the code?

best regards, bibbs
