### ISSUE TITLE
Restore tab (Cmd + Shift + T) should restore the whole previously closed tree instead of one by one

### ISSUE THREAD

**Issue by x-ji** [tabkit/tabkit2#82]

**Comment by PikachuEXE** [comment]
Just keep restoring tab until the whole tree is back
The extension does not do that for you since it's hard to detect whether you have closed a tree or closed a tab.
Closing a tree is in fact closing a group's tabs one by one with script.
Also if this behaviour is included, it is less expected and bad for performance (for large group)
